INSERT INTO brand (id, name, is_deleted) VALUES (1, 'Brand', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (2, 'BRand2', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (3, 'Brand3', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (4, 'BRAND', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (5, 'PROMETHEAN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (6, 'SONY', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (7, 'ADOBE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (8, 'BOSE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (9, 'SENNHEISER', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (10, 'DELL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (11, 'EXTRON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (12, 'DRAPER', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (13, 'MEYER SOUND', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (14, 'SCREENLINE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (15, 'BIAMP', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (16, 'DIS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (17, 'CASATUNES', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (18, 'AUDIPACK', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (19, 'SHARP', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (20, 'AMX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (21, 'MISC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (22, 'AUDITEL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (23, 'CHECKPOINT', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (24, 'FUTURE LIGHT', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (25, 'JBL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (26, 'DENON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (27, 'INTER-M', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (28, 'ELECTRO-VOICE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (29, 'SONANCE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (30, 'CANOVATE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (31, 'VIDEOTECH', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (32, 'TOA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (33, 'LINKSYS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (34, 'MIDDLE ATLANTIC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (35, 'ELO TOUCH', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (36, 'BEYERDYNAMIC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (37, 'DATAPATH', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (38, 'CHRISTIE DIGITAL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (39, 'QSC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (40, 'CHAIN MASTER', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (41, 'AUDIO REQUEST', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (42, 'DAS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (43, 'TELEVIC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (44, 'ANTARI', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (45, 'POLYCOM', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (46, 'TANDBERG', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (47, 'REYTEC IMAGING', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (48, 'D3', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (49, 'CRESTRON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (50, 'TEXAS A&M', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (51, 'TANNOY', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (52, 'RDL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (53, 'HITACHI', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (54, 'LISTENTECH', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (55, 'AUDIO-TECHNICA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (56, 'TECNOVISION', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (57, 'AJA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (58, 'LG', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (59, 'TECHLOGICS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (60, 'AUTO Q', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (61, 'MULTIVISION', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (62, 'PANASONIC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (63, 'ELATION', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (64, 'AUSTRALIAN MONITOR', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (65, 'OCZ', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (66, 'CLEARONE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (67, 'SAMSUNG', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (68, 'SHURE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (69, 'NETBOX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (70, 'CARDAX ME', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (71, 'NOVICOM', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (72, 'DTS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (73, 'OPTOMA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (74, 'CLOUD', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (75, 'INVIDEO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (76, 'EUROTRUSS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (77, 'ELITE SCREENS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (78, 'EUROMET', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (79, 'VOGELS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (80, 'GALLAGHER', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (81, 'CROWN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (82, 'DYNACORD', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (83, 'GLEASON REEL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (84, 'MACKIE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (85, 'CHIEF', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (86, 'ACOUSTIC TECHNOLOGIES', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (87, 'DA-LITE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (88, 'ATI', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (89, 'SONIFEX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (90, 'DYNALITE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (91, 'D-LINK', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (92, 'CM-DIVERSE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (93, 'CISCO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (94, 'BMD', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (95, 'FURMAN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (96, 'SUNBRITE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (97, 'SANYO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (98, 'LOGITECH', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (99, 'TELEVES', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (100, 'TASCAM', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (101, 'AKG', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (102, 'AURALEX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (103, 'NEC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (104, 'APW', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (105, 'APART', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (106, 'ALPHASON DESIGN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (107, 'MARANTZ', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (108, 'ATLAS SOUND', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (109, 'REVOLABS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (110, 'HARMAN HOUSE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (111, 'ELAN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (112, 'AUDIO TECHNICA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (113, 'HUMAX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (114, 'CLOCK AUDIO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (115, 'EXACQVISION', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (116, 'GEMINI', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (117, 'RIEDLE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (118, 'INTELLIVOX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (119, 'BOSCH', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (120, 'BELDEN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (121, 'INSTANT REPLAY', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (122, 'EVERTZ', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (123, 'EATON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (124, 'NEXO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (125, 'ARECONT', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (126, 'OUTREACH', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (127, 'B-TECH', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (128, 'ROKU', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (129, 'POLARCHOICE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (130, 'SPRINT INDUSTRIAL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (131, 'NEXT WINDOW', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (132, 'FCHART', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (133, 'PLANAR', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (134, 'SOUNDCRAFT', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (135, 'DSAN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (136, 'IMRAK', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (137, 'SHOWTECHNIC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (138, 'SCHUKO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (139, 'SOMMER CABLE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (140, 'NEUTRIK', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (141, 'LAPP GROUP', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (142, 'PRO-SIGNAL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (143, 'STEEL CITY', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (144, 'TECHKNOWLEDGIE SOLUTIONS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (145, 'VIEWSONIC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (146, 'PHONAK', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (147, 'JABLOTRON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (148, 'BOON EDAM', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (149, 'WAVEGUIDE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (150, 'XTA ELECTRONICS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (151, 'ACME', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (152, 'STEWART FILMSCREEN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (153, 'AHUJA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (154, 'SUNLIGHT', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (155, 'WOLFVISION', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (156, 'NEVOTEK', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (157, 'PECULIAR', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (158, 'NEXSAN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (159, 'LENOVO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (160, 'CPC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (161, 'STEINBERG', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (162, 'PIONEER', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (163, 'RIVA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (164, '3M', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (165, 'BEHRINGER', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (166, 'EUROLITE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (167, 'OPTEX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (168, 'HICON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (169, 'RENKUS HEINZ', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (170, 'NEW GENERATION IMAGING', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (171, 'RANE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (172, 'IBM', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (173, 'GENIUS VISION DIGITAL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (174, 'ACCESS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (175, 'BRADY', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (176, 'POLYVISION', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (177, 'TARGET', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (178, 'EPIPHAN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (179, 'MIDAS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (180, 'BSS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (181, 'LBC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (182, 'MSR', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (183, 'CREST AUDIO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (184, 'SURGEX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (185, 'VICON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (186, 'MK2', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (187, 'SEAGATE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (188, 'MEDIACAST', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (189, 'ROLINE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (190, 'WEBSTER', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (191, 'AVOLITES', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (192, 'LUMNEX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (193, 'ZEBRA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (194, 'TECHNOSAT', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (195, 'GUARDIAN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (196, 'C-BRACKET', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (197, 'AXXENT', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (198, 'STRAND LIGHTING', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (199, 'IDENTITY', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (200, 'XYTRONIX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (201, 'OPTIMAL CONNECTIVITY', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (202, 'APC SMART', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (203, 'MARTIN PRO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (204, 'OSRAM', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (205, 'RAPPORTIII', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (206, 'CARTONI', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (207, 'SIRIT CORP', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (208, 'ANCHOR AUDIO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (209, 'PROD INTERCOM', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (210, 'LDR', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (211, 'PRYSMIAN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (212, 'UNIVISION', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (213, 'ABTUS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (214, 'NTI AUDIO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (215, 'NVIDIA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (216, 'LIEBERT', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (217, 'PELICAN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (218, 'TITAN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (219, 'LTM', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (220, 'WINSONIC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (221, 'ROBE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (222, 'LODEGUARD', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (223, 'M-AUDIO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (224, 'ADVANTECH', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (225, 'SIGNATURE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (226, 'AXYS INTELLIVOX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (227, 'VERACITY', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (228, 'GSL PROFESSIONAL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (229, 'KALEIDESCAPE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (230, 'ACE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (231, 'VADDIO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (232, 'ODYSSEY', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (233, 'PHILIPS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (234, 'REFLECTION MIRRORS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (235, 'MULTI VIDEO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (236, 'TSA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (237, 'RCF', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (238, 'B&W', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (239, 'DBX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (240, 'NIKKO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (241, 'ONKYO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (242, 'COMMUNITY PRO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (243, 'POWERCON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (244, 'SUPERQUAD', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (245, 'RED LEAF', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (246, 'JABCO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (247, 'GOLDEN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (248, 'ROLAND', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (249, 'GEFEN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (250, 'MUSICABLE II', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (251, 'TEAC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (252, 'IMAGINE TECHNOLOGIES', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (253, 'NORDEN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (254, 'VOLFONI', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (255, 'SENSORMATIC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (256, 'ZYXEL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (257, 'EXPRESS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (258, 'TRIPPLITE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (259, 'KEYSTONE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (260, 'MARSHALL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (261, 'WIJET', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (262, 'DVC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (263, 'ASHLY', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (264, 'SKY SNAKES', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (265, 'VBRICK', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (266, 'JELCO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (267, 'AVN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (268, 'AMINET', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (269, 'DURAN AUDIO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (270, 'HIKVISION', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (271, 'EXCEL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (272, 'B3', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (273, 'NAIMNET', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (274, 'FALCON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (275, 'EPSON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (276, 'AMPETRONIC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (277, 'FLIGHTCASE WAREHOUSE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (278, 'DISNEY', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (279, 'PCE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (280, 'ELITE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (281, 'BLACK BOX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (282, 'BTECH', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (283, 'AWIND', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (284, 'SOCAPEX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (285, 'BRIGHTSIGN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (286, 'TVONE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (287, 'ELEWIND', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (288, 'RODE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (289, 'PERCON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (290, 'STEALTH ACOUSTICS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (291, 'SIEMON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (292, 'MADRIX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (293, 'AXON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (294, 'ROLLS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (295, 'SESCOM', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (296, 'DNH', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (297, 'LIGHTWARE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (298, 'LUCIBEL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (299, 'DOTWORKZ', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (300, 'HP', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (301, 'ADMIN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (302, 'WINSTED', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (303, 'CANFORD', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (304, 'HAMILTON BUHL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (305, 'VIDEOTREE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (306, 'CTOUCH', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (307, 'NORTON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (308, 'BALANCEBOX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (309, 'DRITALIA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (310, 'ROTEL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (311, 'PLANTRONICS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (312, 'MIRRORVUE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (313, 'C2G', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (314, 'CHRISTIE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (315, 'ANCHOR', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (316, 'YAMAHA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (317, 'APPLE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (318, 'ARTHUR HOLM', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (319, 'PRESOUNS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (320, 'RUCKUS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (321, 'WILLIAMS SOUND', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (322, 'IBS FLIGHTCASES', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (323, 'RASPBERRY PI', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (324, 'IHOME', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (325, 'GUJARAT TECHNO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (326, 'KLOTZ', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (327, 'POWER-SONIC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (328, 'SAMSON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (329, 'EDMOLIFT', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (330, 'RME', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (331, 'BRAVO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (332, 'SPECKTRON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (333, 'JVC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (334, 'SPRINT', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (335, 'ALECTRO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (336, 'STARTECH', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (337, 'SUPREMA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (338, 'Q-MATIC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (339, 'GOOGLE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (340, 'TP-LINK', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (341, 'DINTEK', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (342, 'DAHUA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (343, 'WD', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (344, 'MACROPIX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (345, 'COMMSPEED', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (346, 'MICROSOFT', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (347, 'VESTEL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (348, 'INFOSEC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (349, 'VENUS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (350, 'JIAXING WALLSTECH', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (351, 'STAIRVILLE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (352, 'CHAUVET DJ', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (353, 'ZERO 88', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (354, 'HANWHA TECHWIN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (355, 'TRUE PERFORMANCE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (356, 'SERENE INNOVATIONS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (357, 'ULTRATEC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (358, 'HARRIS COMMUNICATION', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (359, 'CLARITY', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (360, 'BLACKMAGIC DESIGN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (361, 'GENELEC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (362, 'STAYONLINE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (363, 'AMINO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (364, 'BENQ', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (365, 'AXIOMTEK', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (366, 'TOSHIBA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (367, 'ADAFRUIT', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (368, 'A-NEUVIDEO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (369, 'SMART', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (370, 'ZEROCAM', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (371, 'WACOM', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (372, 'MAX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (373, 'STACKFINE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (374, 'TERMINATOR', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (375, 'LECXO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (376, 'OTTERBOX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (377, 'EDITSHARE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (378, 'INDOTA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (379, 'RIP-TIE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (380, 'GAFFER', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (381, 'MANFROTTO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (382, 'ALKALINE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (383, 'CANON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (384, 'PORTA BRACE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (385, 'K-TEK', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (386, 'SACHTLER', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (387, 'MILLER', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (388, 'BARCO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (389, 'MERSIVE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (390, 'IMPACT', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (391, 'SANDISK', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (392, 'RAYA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (393, 'SUNPAK', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (394, 'TIFFEN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (395, 'BUCKET BOSS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (396, 'G-TECHNOLOGY', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (397, 'BESSEY', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (398, 'NIKON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (399, 'RUGGARD', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (400, 'SAVAGE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (401, 'SHAPE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (402, 'VELLO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (403, 'AURAY', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (404, 'GATOR', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (405, 'LAIRD DIGITAL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (406, 'DELKIN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (407, 'ATLAS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (408, 'ZOOM', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (409, 'NEEWER', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (410, 'GENARAY', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (411, 'KOPUL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (412, 'ATOMOS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (413, 'MAGMA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (414, 'DOLGIN ENGINEERING', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (415, 'TECH NEC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (416, 'REALLY RIGHT STUFF', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (417, 'RYCOTE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (418, 'BULLETX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (419, 'ADASTRA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (420, 'JL AUDIO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (421, 'PENTON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (422, 'ARRI', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (423, 'DJI OSMO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (424, 'SERVERTECH', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (425, 'LEGRAND', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (426, 'ANSR AUDIO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (427, 'OLSON', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (428, 'KLANGHELM', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (429, 'NEAT VIDEO', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (430, 'IMAGENOMIC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (431, 'TELESTREAM', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (432, 'ANTARES', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (433, 'PLANET', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (434, 'PHIDGET', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (435, 'MOTU', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (436, 'UBIQUITI NETWORKS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (437, 'EVENT OPAL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (438, 'LAB GRUPPEN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (439, 'ZENAN', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (440, 'DIGITAL PROJECTION', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (441, 'FISCHER', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (442, 'LOWELL', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (443, 'ASHANKS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (444, 'FOS', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (445, 'KEYPOINT INTERACTIVE', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (446, 'GTEC ', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (447, 'ULTIMA ', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (448, 'BRETFORD', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (449, 'IBOXX', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (450, 'BRETFORD', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (451, 'GTEC', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (452, 'ULTIMA', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (453, 'INFOMIR', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (454, 'VISIONCHART', 0);
INSERT INTO brand (id, name, is_deleted) VALUES (455, 'NEOSTAR', 0);