set foreign_key_checks = 0;
TRUNCATE TABLE attachment;
TRUNCATE TABLE brand;
TRUNCATE TABLE category;
TRUNCATE TABLE company;
TRUNCATE TABLE customer;
TRUNCATE TABLE employee;
TRUNCATE TABLE invoice_item-item;
TRUNCATE TABLE meta;
TRUNCATE TABLE procurement;
TRUNCATE TABLE procurement_payment;
TRUNCATE TABLE project;
TRUNCATE TABLE project_expense;
TRUNCATE TABLE project_payment;
TRUNCATE TABLE supplier;
TRUNCATE TABLE user;
set foreign_key_checks = 1;
