set foreign_key_checks = 0;
TRUNCATE TABLE if exists attachment;
TRUNCATE TABLE if exists brand;
TRUNCATE TABLE if exists category;
TRUNCATE TABLE if exists company;
TRUNCATE TABLE if exists customer;
TRUNCATE TABLE if exists employee;
TRUNCATE TABLE if exists invoice_item-item;
TRUNCATE TABLE if exists meta;
TRUNCATE TABLE if exists procurement;
TRUNCATE TABLE if exists procurement_payment;
TRUNCATE TABLE if exists project;
TRUNCATE TABLE if exists project_expense;
TRUNCATE TABLE if exists project_payment;
TRUNCATE TABLE if exists supplier;
TRUNCATE TABLE if exists user;
set foreign_key_checks = 1;
