set foreign_key_checks = 0;
drop TABLE attachment;
drop TABLE brand;
drop TABLE category;
drop TABLE company;
drop TABLE customer;
drop TABLE employee;
drop TABLE invoice;
drop TABLE meta;
drop TABLE procurement;
drop TABLE procurement_payment;
drop TABLE project;
drop TABLE project_expense;
drop TABLE project_payment;
drop TABLE supplier;
drop TABLE user;
set foreign_key_checks = 1;
