set foreign_key_checks = 0;
drop TABLE if exists attachment;
drop TABLE if exists brand;
drop TABLE if exists category;
drop TABLE if exists company;
drop TABLE if exists customer;
drop TABLE if exists employee;
drop TABLE if exists invoice_item;
drop TABLE if exists meta;
drop TABLE if exists procurement;
drop TABLE if exists procurement_payment;
drop TABLE if exists project;
drop TABLE if exists project_expense;
drop TABLE if exists project_payment;
drop TABLE if exists supplier;
drop TABLE if exists user;
set foreign_key_checks = 1;
